# MySQL
spring.datasource.url=jdbc:mysql://chatbot-db/chatbot
# Redis
spring.data.redis.host=redis

# k8s
spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.discovery.service-labels.app=user-service

logging.level.org.springframework.cloud.kubernetes=DEBUG

# Feign Client
spring.cloud.openfeign.client.config.user-service.url=http://user-service:8082