spring.application.name=auth-service

# Profiles
spring.profiles.active=${SPRING_PROFILE:local}
# Server
server.port=8081
# MySQL
spring.datasource.username=local
spring.datasource.password=local
# SQL
spring.sql.init.mode=always
# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Redis
spring.data.redis.port=6379

# SMTP
mcshop.mail.host=smtp.gmail.com
mcshop.mail.port=587
mcshop.mail.protocol=smtp
mcshop.mail.smtp-auth=true
mcshop.mail.smtp-starttls-enable=true
mcshop.mail.smtp-debug=false
mcshop.mail.username=${SMTP_USERNAME}
mcshop.mail.password=${SMTP_PASSWORD}
# OTP
mcshop.otp.expire.second=300

# Feign client
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.client.config.default.logger-level=full

# Micro Service
user.service.name=user-service
user.service.path=/api/v1/user

# JWT
mcshop.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
mcshop.jwt.access-token-expiration=86400000
mcshop.jwt.refresh-token-expiration=604800000