services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    networks:
      - mcshop-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway-service:
    build:
      context: gateway-service
      target: docker
      dockerfile: Dockerfile
    container_name: "gateway-service"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-service
      - user-service
    networks:
      - mcshop-network

  auth-service:
    build:
      context: auth-service
      target: docker
      dockerfile: Dockerfile
    container_name: "auth-service"
    env_file:
      - .env
    environment:
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mcshop-db
      - redis
    networks:
      - mcshop-network

  user-service:
    build:
      context: user-service
      target: docker
      dockerfile: Dockerfile
    container_name: "user-service"
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - mcshop-db
      - redis
    networks:
      - mcshop-network

  product-service:
    build:
      context: product-service
      target: docker
      dockerfile: Dockerfile
    container_name: "product-service"
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      - mcshop-db
      - redis
    networks:
      - mcshop-network

  mcshop-db:
    image: mysql:8.0
    container_name: "mcshop-db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_DATABASE=mcshop
    volumes:
      - mcshop_db_data:/var/lib/mysql
      - ./data/mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - mcshop-network

  redis:
    restart: always
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - mcshop-network

volumes:
  mcshop_db_data:

networks:
  mcshop-network:
    driver: bridge