apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: mcshop
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/mcshop"
  SPRING_DATASOURCE_USERNAME: "local"
  SPRING_DATASOURCE_PASSWORD: "local"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  user.service.name: "user-service"
  user.service.path: "/api/v1/user"
  SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mcshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ismarcochow/mcshop-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: auth-service-config
          env:
            - name: SPRING_PROFILE
              value: docker
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: smtp-password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mcshop
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: auth-service