apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: mcshop
data:
  SPRING_CLOUD_GATEWAY_ROUTES_0_ID: "auth-service"
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "lb://auth-service"
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: "Path=/api/v1/auth/**"
  SPRING_CLOUD_GATEWAY_ROUTES_1_ID: "user-service"
  SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "lb://user-service"
  SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: "Path=/api/v1/user/**"
  SPRING_CLOUD_GATEWAY_ROUTES_2_ID: "swagger"
  SPRING_CLOUD_GATEWAY_ROUTES_2_URI: "lb://auth-service"
  SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: "Path=/v3/api-docs/**"
  SPRING_CLOUD_GATEWAY_ROUTES_3_ID: "swagger-ui"
  SPRING_CLOUD_GATEWAY_ROUTES_3_URI: "lb://auth-service"
  SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0: "Path=/swagger-ui/**"
  SPRING_CLOUD_KUBERNETES_DISCOVERY_ALLOWEDNAMESPACES: "mcshop"
  SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: mcshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ismarcochow/mcshop-gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: mcshop
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway-service