---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: chatbot
data: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_USER
              value: local
            - name: MYSQL_PASSWORD
              value: local
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: chatbot
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init
            items:
              - key: mcshop.sql
                path: mcshop.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: chatbot
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP