spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**
        - id: chat-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/chat/**
        - id: subscription-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/subscription/**
        - id: payment-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/payment/**
  datasource:
    url: jdbc:localhost://chatbot-db/chatbot
  data:
    redis:
      host: localhost