# AWS secretsmanager
spring.config.import=aws-secretsmanager:mail-secrets?prefix=mcshop.mail.
# AWS Core
spring.cloud.aws.endpoint=http://localhost:4566
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mcshop
# Redis
spring.data.redis.host=localhost