# AWS secretsmanager
spring.config.import=aws-secretsmanager:mail-secrets?prefix=mcshop.mail.
# AWS Core
spring.cloud.aws.endpoint=http://localstack:4566
# MySQL
spring.datasource.url=jdbc:mysql://mysql/mcshop
# Redis
spring.data.redis.host=redis