spring.application.name=order-service

# Profiles
spring.profiles.active=${SPRING_PROFILE:local}
# Server
server.port=8084
# MySQL
spring.datasource.username=local
spring.datasource.password=local
# SQL
spring.sql.init.mode=always
# Redis
spring.data.redis.port=6379
# Swagger
springdoc.api-docs.path=/api-docs

# Stripe
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Micro Service
product.service.name=product-service
product.service.path=/api/v1/product
product.inventory.service.name=product-inventory-service
product.inventory.service.path=/api/v1/product/inventory

# RabbitMQ
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest